### PR TITLE
Feat fixture data & update dependencies

### PR DESCRIPTION
**Pull request by fuenkchen**
* prettier code in separate commit
* update to hapi 17
* generate fixture data via build script

### CODE REVIEW

**Review by manuelroth — APPROVED** [review]

**Review by benib — APPROVED** [review]
@fuenkchen can you add an example of the .env file to README?

**Comment by fuenkchen** [comment]
👍 was also not so sure about what should be mentioned in README. Do you think it's sufficient then with an example of env.json

**Comment by benib** [comment]
@fuenkchen Maybe something: If you work with Q-cli, there is a config file here... add an .env file in the repository root with the following content: ... (adjust the map ids and tokens)

**Comment by fuenkchen** [comment]
Added it, what do you think?

**Pull request merged**
